export const ACTIONS = {
  ADD_TODO: "ADD_TODO",
  SET_CHECKED: "SET_CHECKED",
  SET_SELECTED: "SET_SELECTED",
  REMOVE_TODO: "REMOVE_TODO",
};

export const ACTIONS_POSTS = {
  GET_POSTS_REQUEST: "GET_POSTS_REQUEST",
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  GET_POSTS_FAILURE: "GET_POSTS_FAILURE",
};
